Add TestFeltIs0
lambdaclass/cairo-vm_in_go pull request #135
Opened 2023-08-14 21:07 UTC by coburn24

closes #117

2023-08-14 21:26 UTC, gabrielbosio requested changes

2023-08-14 21:26 UTC, gabrielbosio commented on pkg/lambdaworks/lambdaworks_test.go
> +	if result != expected {
This test fails. It should expect the result to be different on purpose. Please, revert this change.

2023-08-14 22:57 UTC, mattcoburn24 commented on pkg/lambdaworks/lambdaworks_test.go
> +	if result != expected {
Oops, reverted 👍🏼

2023-08-15 13:50 UTC, gabrielbosio requested changes
The test looks good. To close the issue, we would need one more test to check when `IsZero` returns `false`.

2023-08-15 15:28 UTC, coburn24 commented
@gabrielbosio should be good now, added a TestFeltIs0Error test just below TestFeltIs0

2023-08-15 17:29 UTC, toni-calvin commented on pkg/lambdaworks/lambdaworks_test.go
> +func TestFeltis0Error(t *testing.T) {
```suggestion
func TestFeltIsNotZero(t *testing.T) {
```

2023-08-15 17:29 UTC, toni-calvin commented on pkg/lambdaworks/lambdaworks_test.go
> +func TestFeltIs0(t *testing.T) {
```suggestion
func TestFeltIsZero(t *testing.T) {
```

2023-08-15 17:30 UTC, toni-calvin commented on pkg/lambdaworks/lambdaworks_test.go
> +	f_one := lambdaworks.FeltFromUint64(1)
```suggestion
	f_one := lambdaworks.FeltOne()
```

2023-08-15 17:31 UTC, toni-calvin commented on pkg/lambdaworks/lambdaworks_test.go
> +	if result == expected {
Test should compare if result != expected to throw an error, otherwise is correct

2023-08-15 17:32 UTC, toni-calvin requested changes
Ive added some comments

2023-08-15 17:51 UTC, mattcoburn24 commented
@toni-calvin thank you for the feedback, I have updated the commit accordingly 👍🏼

2023-08-15 19:04 UTC, gabrielbosio commented on pkg/lambdaworks/lambdaworks_test.go
> +	if result != expected {
This can be simplified:

```suggestion
	is_zero := f_zero.IsZero()

	if !is_zero {
```

2023-08-15 19:04 UTC, gabrielbosio commented on pkg/lambdaworks/lambdaworks_test.go
> +		t.Errorf("TestFeltIs0 failed. Expected: %v, Got %v", expected, result)
```suggestion
		t.Errorf("TestFeltIsZero failed. Expected: %v, Got %v", expected, result)
```

2023-08-15 19:06 UTC, gabrielbosio commented on pkg/lambdaworks/lambdaworks_test.go
> +	if result != expected {
This can be simplified:

```suggestion
	is_zero := f_one.IsZero()

	if is_zero {
```

2023-08-15 19:06 UTC, gabrielbosio commented on pkg/lambdaworks/lambdaworks_test.go
> +		t.Errorf("TestFeltIs0 failed. Expected: %v, Got: %v", expected, result)
```suggestion
		t.Errorf("TestFeltIsNotZero failed. Expected: %v, Got: %v", expected, result)
```

2023-08-15 19:06 UTC, gabrielbosio commented on pkg/lambdaworks/lambdaworks_test.go
> +func TestFeltisNotZero(t *testing.T) {
```suggestion
func TestFeltIsNotZero(t *testing.T) {
```

2023-08-15 21:07 UTC, coburn24 commented
have made edits 👍🏼 @gabrielbosio

2023-08-15 21:28 UTC, toni-calvin approved these changes
👍

2023-08-15 21:28 UTC, toni-calvin commented on pkg/lambdaworks/lambdaworks_test.go
> +func TestFeltisNotZero(t *testing.T) {
```suggestion
func TestFeltIsNotZero(t *testing.T) {
```

2023-08-15 21:28 UTC, toni-calvin commented on pkg/lambdaworks/lambdaworks_test.go
> +func TestFeltisNotZero(t *testing.T) {
Just to follow language conventions

2023-08-15 21:28 UTC, toni-calvin commented on pkg/lambdaworks/lambdaworks_test.go
> +		t.Errorf("TestFeltIs0 failed. Expected: %v, Got: %v", expected, result)
```suggestion
		t.Errorf("TestFeltIsNotZero failed. Expected: %v, Got: %v", expected, result)
```

2023-08-15 21:28 UTC, toni-calvin commented on pkg/lambdaworks/lambdaworks_test.go
> +		t.Errorf("TestFeltIs0 failed. Expected: %v, Got %v", expected, result)
```suggestion
		t.Errorf("TestFeltIsZero failed. Expected: %v, Got %v", expected, result)
```

2023-08-16 00:48 UTC, coburn24 commented
👍🏼

2023-08-16 16:00 UTC, gabrielbosio approved these changes
Looks good!

2023-08-16 16:01 UTC, merged