Add ADD_SEGMENT hint
lambdaclass/cairo-vm_in_go pull request #192
Opened 2023-09-12 13:55 UTC by Juan-M-V

Resolves #170

2023-09-12 14:06 UTC, pefontana reviewed
Can we add an integration test?
I think this should work
https://github.com/lambdaclass/cairo-vm/blob/main/cairo_programs/if_reloc_equal.cairo

2023-09-12 20:47 UTC, jrchatruc approved these changes

2023-09-12 21:12 UTC, fmoletta requested changes

2023-09-12 21:12 UTC, fmoletta commented on pkg/vm/memory/relocatable.go
> +		return *NewMaybeRelocatableFelt(offset_diff), nil
Don't change this, the bug is in `Relocatable.Sub` and will pop up later if left unfixed

2023-09-12 21:13 UTC, fmoletta commented on pkg/vm/memory/relocatable.go
> +		return *NewMaybeRelocatableFelt(offset_diff), nil
This fix should go to `Relocatable.Sub`

2023-09-13 14:07 UTC, pefontana approved these changes

2023-09-13 14:07 UTC, fmoletta approved these changes

2023-09-13 14:10 UTC, merged